/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_projet;

import java.awt.Color;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author moham
 */
public class DashProf extends javax.swing.JFrame {
        Connection con;
        Statement stm;
        ResultSet rst;
        int i=0;
        Etudiant e=new Etudiant();
        Professeur p=new Professeur();
        Classe c=new Classe();

    public DashProf() {
        initComponents();
//        DashBoard ds=new DashBoard();
//        ds.setDefaultCloseOperation(EXITs_ON_CLOSE);
//        ds.setSize(400,400);
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","hr","hr");
            stm=con.createStatement();
        }catch(ClassNotFoundException | SQLException ee){
            System.out.println("Erreur de chargement de pilote:"+ee);
        }
        
             }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Accueilpn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        etudiantpn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jtabdash = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        Dnom = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jTEtud = new javax.swing.JTabbedPane();
        jPanel32 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab_etud = new javax.swing.JTable();
        jPanel34 = new javax.swing.JPanel();
        cne2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        ok_n = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        n = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        cneabs = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        ab = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        ok_abs = new javax.swing.JButton();
        Logoutpn = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(53, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Accueilpn.setBackground(new java.awt.Color(63, 42, 100));
        Accueilpn.setToolTipText("");
        Accueilpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccueilpnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccueilpnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccueilpnMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Accueil");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/folder/icons8_home_30px_1.png"))); // NOI18N

        javax.swing.GroupLayout AccueilpnLayout = new javax.swing.GroupLayout(Accueilpn);
        Accueilpn.setLayout(AccueilpnLayout);
        AccueilpnLayout.setHorizontalGroup(
            AccueilpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilpnLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AccueilpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        AccueilpnLayout.setVerticalGroup(
            AccueilpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccueilpnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccueilpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(AccueilpnLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(Accueilpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 50));

        etudiantpn.setBackground(new java.awt.Color(63, 42, 100));
        etudiantpn.setToolTipText("");
        etudiantpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etudiantpnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etudiantpnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etudiantpnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Étudiant");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/folder/icons8_student_male_30px.png"))); // NOI18N

        javax.swing.GroupLayout etudiantpnLayout = new javax.swing.GroupLayout(etudiantpn);
        etudiantpn.setLayout(etudiantpnLayout);
        etudiantpnLayout.setHorizontalGroup(
            etudiantpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etudiantpnLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(etudiantpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        etudiantpnLayout.setVerticalGroup(
            etudiantpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(etudiantpnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(etudiantpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(etudiantpnLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(etudiantpnLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.add(etudiantpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 10));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Professeur");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 130, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/folder/icons8_school_director_26px.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 450));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jtabdash.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jtabdash.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        jtabdash.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtabdash.setDoubleBuffered(true);
        jtabdash.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jtabdashComponentHidden(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setBackground(new java.awt.Color(122, 73, 221));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Bienvenu");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Monsieur");

        Dnom.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Dnom.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/folder/est-essaouira.png"))); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dnom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(Dnom)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 379, Short.MAX_VALUE))
        );

        jtabdash.addTab("Accueil", jPanel7);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(122, 73, 221));

        jButton12.setBackground(new java.awt.Color(63, 42, 100));
        jButton12.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Afficher");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(63, 42, 100));
        jButton7.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Note");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(63, 42, 100));
        jButton8.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Absence");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator9)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTEtud.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTEtud.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));

        tab_etud.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        tab_etud.setForeground(new java.awt.Color(53, 33, 89));
        tab_etud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CNE", "Nom", "Prénom", "Classe", "Payment", "Note", "Absence"
            }
        ));
        tab_etud.setGridColor(new java.awt.Color(53, 33, 89));
        tab_etud.setSelectionBackground(new java.awt.Color(53, 33, 89));
        jScrollPane5.setViewportView(tab_etud);

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel32Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jTEtud.addTab("Affiche", jPanel32);

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));

        cne2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        cne2.setForeground(new java.awt.Color(53, 33, 89));
        cne2.setSelectionColor(new java.awt.Color(53, 33, 89));
        cne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cne2jTextField2ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(53, 33, 89));
        jLabel28.setText("CNE");

        ok_n.setBackground(new java.awt.Color(63, 42, 100));
        ok_n.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        ok_n.setForeground(new java.awt.Color(255, 255, 255));
        ok_n.setText("Ajoute note");
        ok_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_nAjoute_C1ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(53, 33, 89));
        jLabel29.setText("Note");

        n.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        n.setForeground(new java.awt.Color(53, 33, 89));
        n.setSelectionColor(new java.awt.Color(53, 33, 89));
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                njTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cne2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ok_n)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ok_n, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jTEtud.addTab("Note", jPanel34);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        cneabs.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        cneabs.setForeground(new java.awt.Color(53, 33, 89));
        cneabs.setSelectionColor(new java.awt.Color(53, 33, 89));
        cneabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cneabsjTextField2ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(53, 33, 89));
        jLabel30.setText("CNE");

        ab.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        ab.setForeground(new java.awt.Color(53, 33, 89));
        ab.setSelectionColor(new java.awt.Color(53, 33, 89));
        ab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abjTextField2ActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(53, 33, 89));
        jLabel31.setText("Absence (nombre de heures)");

        ok_abs.setBackground(new java.awt.Color(63, 42, 100));
        ok_abs.setFont(new java.awt.Font("Yu Gothic Medium", 0, 12)); // NOI18N
        ok_abs.setForeground(new java.awt.Color(255, 255, 255));
        ok_abs.setText("Ajoute Absence");
        ok_abs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_absActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cneabs, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ok_abs)
                            .addComponent(ab, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cneabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ok_abs)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTEtud.addTab("Absence", jPanel8);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTEtud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTEtud, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );

        jtabdash.addTab("Etudiant", jPanel5);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtabdash)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jtabdash, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtabdash.getAccessibleContext().setAccessibleName("Classes");

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 560, 420));

        Logoutpn.setBackground(new java.awt.Color(255, 255, 255));
        Logoutpn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutpnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutpnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutpnMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/folder/icons8_exit_24px_1.png"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(108, 64));
        jLabel10.setMinimumSize(new java.awt.Dimension(108, 64));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LogoutpnLayout = new javax.swing.GroupLayout(Logoutpn);
        Logoutpn.setLayout(LogoutpnLayout);
        LogoutpnLayout.setHorizontalGroup(
            LogoutpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutpnLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoutpnLayout.setVerticalGroup(
            LogoutpnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutpnLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Logoutpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AccueilpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilpnMouseClicked
        jtabdash.setSelectedIndex(0);
        Accueilpn.setBackground(new Color(85,65,118));
        int i=0;
        try{
        String query="select * from Directeur";
        rst=stm.executeQuery(query);
        while(rst.next()){
             Dnom.setText(rst.getString("nom_d"));

               i=i+1;
           }
        }catch(SQLException e){
            System.out.println("Erreur !!:"+e);
        }

    }//GEN-LAST:event_AccueilpnMouseClicked

    private void etudiantpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etudiantpnMouseClicked
        jtabdash.setSelectedIndex(1);
                etudiantpn.setBackground(new Color(85,65,118));

    }//GEN-LAST:event_etudiantpnMouseClicked

    private void AccueilpnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilpnMouseEntered
        Accueilpn.setBackground(new Color(85,65,118));
    }//GEN-LAST:event_AccueilpnMouseEntered

    private void etudiantpnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etudiantpnMouseEntered
        etudiantpn.setBackground(new Color(85,65,118));    }//GEN-LAST:event_etudiantpnMouseEntered

    private void AccueilpnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccueilpnMouseExited
        Accueilpn.setBackground(new Color(63,42,100));
    }//GEN-LAST:event_AccueilpnMouseExited

    private void etudiantpnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etudiantpnMouseExited
        etudiantpn.setBackground(new Color(63,42,100));
    }//GEN-LAST:event_etudiantpnMouseExited

    private void jtabdashComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jtabdashComponentHidden
    }//GEN-LAST:event_jtabdashComponentHidden

    private void LogoutpnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutpnMouseEntered
    }//GEN-LAST:event_LogoutpnMouseEntered

    private void LogoutpnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutpnMouseExited
    }//GEN-LAST:event_LogoutpnMouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        int conf=JOptionPane.showConfirmDialog(null, "Are you sure to exit ?","Exit Message box",JOptionPane.YES_NO_OPTION);
            if(conf==JOptionPane.YES_NO_OPTION){
                dispose();
            }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void LogoutpnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutpnMouseClicked
            
            
    }//GEN-LAST:event_LogoutpnMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
                jTEtud.setSelectedIndex(0);
                  int i=0;

                try{
            String query="select * from Etudiant ";
            rst=stm.executeQuery(query);
            while(rst.next()){
                int CNE=rst.getInt("CNE");
                String Nom=rst.getString("nom_e");
                String Prénom=rst.getString("prenom_e");
                String Classe=rst.getString("nom_c");
                int Payment=rst.getInt("payment");
                int Note=rst.getInt("note");
                int Absence=rst.getInt("abs");
                
                tab_etud.setValueAt(CNE, i, 0);
                tab_etud.setValueAt(Nom, i, 1);
                tab_etud.setValueAt(Prénom, i, 2);
                tab_etud.setValueAt(Classe, i, 3);
                tab_etud.setValueAt(Payment, i, 4);
                tab_etud.setValueAt(Note, i, 5);
                tab_etud.setValueAt(Absence, i, 6);
              
               i=i+1;
           }
            
        }catch(SQLException e){
            System.out.println("Erreur !!:"+e);
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTEtud.setSelectedIndex(1);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cne2jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cne2jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cne2jTextField2ActionPerformed

    private void ok_nAjoute_C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_nAjoute_C1ActionPerformed
        int CNE=Integer.parseInt(cne2.getText());
        int note=Integer.parseInt(n.getText());
        if(evt.getSource()==ok_n){
            e.ajoute_note(CNE, note);
        }
        cne2.setText("");
        n.setText("");
                    }//GEN-LAST:event_ok_nAjoute_C1ActionPerformed

    private void njTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_njTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_njTextField2ActionPerformed

    private void cneabsjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cneabsjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cneabsjTextField2ActionPerformed

    private void abjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_abjTextField2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTEtud.setSelectedIndex(2);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ok_absActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_absActionPerformed
        int CNE=Integer.parseInt(cneabs.getText());
        int abs=Integer.parseInt(ab.getText());
        if(evt.getSource()==ok_abs){
            e.ajoute_abs(CNE, abs);
        }
        cneabs.setText("");
            ab.setText("");




    }//GEN-LAST:event_ok_absActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashProf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashProf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueilpn;
    private javax.swing.JLabel Dnom;
    private javax.swing.JPanel Logoutpn;
    private javax.swing.JTextField ab;
    private javax.swing.JTextField cne2;
    private javax.swing.JTextField cneabs;
    private javax.swing.JPanel etudiantpn;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTEtud;
    private javax.swing.JTabbedPane jtabdash;
    private javax.swing.JTextField n;
    private javax.swing.JButton ok_abs;
    private javax.swing.JButton ok_n;
    private javax.swing.JTable tab_etud;
    // End of variables declaration//GEN-END:variables
}
