/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mini_projet;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hanane Jagour
 */
public class Gestion_Ecole_privé extends javax.swing.JFrame {

    /**
     * Creates new form Gestion_Ecole_privé
     */
    public Gestion_Ecole_privé() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        ok_p = new javax.swing.JButton();
        ok_absence = new javax.swing.JButton();
        ajoute_e = new javax.swing.JButton();
        sup_e = new javax.swing.JButton();
        aj_pay = new javax.swing.JButton();
        aff_e = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        aj_classe = new javax.swing.JButton();
        aff_c = new javax.swing.JButton();
        affiche_e_c = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        aj_prof = new javax.swing.JButton();
        sup_pr = new javax.swing.JButton();
        aj_sal = new javax.swing.JButton();
        aff_prof = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ok_p.setText("note_e");
        ok_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_pActionPerformed(evt);
            }
        });

        ok_absence.setText("abs_e");
        ok_absence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_absenceActionPerformed(evt);
            }
        });

        ajoute_e.setText("ajout_e");
        ajoute_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoute_eActionPerformed(evt);
            }
        });

        sup_e.setText("supprimer_e");
        sup_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup_eActionPerformed(evt);
            }
        });

        aj_pay.setText("aj_payment");
        aj_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aj_payActionPerformed(evt);
            }
        });

        aff_e.setText("aff_e");
        aff_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aff_eActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ok_p, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ok_absence, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ajoute_e, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sup_e, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aff_e, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(aj_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_p)
                    .addComponent(ok_absence)
                    .addComponent(ajoute_e))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aj_pay)
                    .addComponent(sup_e)
                    .addComponent(aff_e))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1);
        jPanel1.setBounds(20, 20, 360, 70);

        aj_classe.setText("aj_classe");
        aj_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aj_classeActionPerformed(evt);
            }
        });

        aff_c.setText("aff_c");
        aff_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aff_cActionPerformed(evt);
            }
        });

        affiche_e_c.setText("aff_e_classe");
        affiche_e_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affiche_e_cActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aj_classe)
                .addGap(35, 35, 35)
                .addComponent(aff_c, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(affiche_e_c, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aj_classe)
                    .addComponent(aff_c)
                    .addComponent(affiche_e_c))
                .addContainerGap())
        );

        desktopPane.add(jPanel2);
        jPanel2.setBounds(20, 110, 360, 40);

        aj_prof.setText("aj_prof");
        aj_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aj_profActionPerformed(evt);
            }
        });

        sup_pr.setText("supp_pr");
        sup_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup_prActionPerformed(evt);
            }
        });

        aj_sal.setText("aj_salaire");
        aj_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aj_salActionPerformed(evt);
            }
        });

        aff_prof.setText("aff_prof");
        aff_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aff_profActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(aj_prof)
                .addGap(34, 34, 34)
                .addComponent(sup_pr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(aj_sal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(127, 127, 127)
                    .addComponent(aff_prof, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(128, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aj_prof)
                    .addComponent(sup_pr)
                    .addComponent(aj_sal))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(aff_prof)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );

        desktopPane.add(jPanel3);
        jPanel3.setBounds(30, 180, 330, 100);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_pActionPerformed
        if(evt.getSource()==ok_p){
        try {
            aj_note aj_n=new aj_note();
//            aj_n.setMaximumSize(aj_n.getMaximumSize());
            desktopPane.add(aj_n);
           aj_n.setVisible(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Gestion_Ecole_privé.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_ok_pActionPerformed

    private void ok_absenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_absenceActionPerformed
         if(evt.getSource()==ok_absence){
             aj_abs aj_ab=new aj_abs();
//             aj_ab.setMaximumSize(aj_ab.getMaximumSize());
             desktopPane.add(aj_ab);
             aj_ab.setVisible(true);
        }
        
    }//GEN-LAST:event_ok_absenceActionPerformed

    private void ajoute_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoute_eActionPerformed
       if(evt.getSource()==ajoute_e){
           aj_e j_e=new aj_e();
           desktopPane.add(j_e);
           j_e.setVisible(true);
       }
    }//GEN-LAST:event_ajoute_eActionPerformed

    private void sup_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup_eActionPerformed
        if(evt.getSource()==sup_e){
            supp_e su_e=new supp_e();
            desktopPane.add(su_e);
            su_e.setVisible(true);
        }
    }//GEN-LAST:event_sup_eActionPerformed

    private void aj_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aj_payActionPerformed
        if(evt.getSource()==aj_pay){
            aj_payment aj_py=new aj_payment();
            desktopPane.add(aj_py);
            aj_py.setVisible(true);
        }
    }//GEN-LAST:event_aj_payActionPerformed

    private void aj_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aj_classeActionPerformed
        if(evt.getSource()==aj_classe){
            aj_classe aj_c=new aj_classe();
            desktopPane.add(aj_c);
            aj_c.setVisible(true);
        }
    }//GEN-LAST:event_aj_classeActionPerformed

    private void aff_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aff_cActionPerformed
        if(evt.getSource()==aff_c){
            aff_c af_c=new aff_c();
            desktopPane.add(af_c);
            af_c.setVisible(true);
        }
    }//GEN-LAST:event_aff_cActionPerformed

    private void affiche_e_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affiche_e_cActionPerformed
        if(evt.getSource()==affiche_e_c){
            aff_e_classe af_eCL=new aff_e_classe();
            desktopPane.add(af_eCL);
            af_eCL.setVisible(true);
         
        }
    }//GEN-LAST:event_affiche_e_cActionPerformed

    private void aff_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aff_eActionPerformed
        if(evt.getSource()==aff_e){
            aff_etud af_e=new aff_etud();
            desktopPane.add(af_e);
            af_e.setVisible(true);
         
        }
    }//GEN-LAST:event_aff_eActionPerformed

    private void aj_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aj_profActionPerformed
        if(evt.getSource()==aj_prof){
            aj_prof aj_p=new aj_prof();
            desktopPane.add(aj_p);
            aj_p.setVisible(true);
        }
    }//GEN-LAST:event_aj_profActionPerformed

    private void sup_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup_prActionPerformed
         if(evt.getSource()==sup_pr){
             supp_prof sup_pr=new supp_prof();
             desktopPane.add(sup_pr);
             sup_pr.setVisible(true);
         }
    }//GEN-LAST:event_sup_prActionPerformed

    private void aj_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aj_salActionPerformed
        if(evt.getSource()==aj_sal){
            aj_salaire aj_s=new aj_salaire();
            desktopPane.add(aj_s);
            aj_s.setVisible(true);
        }
    }//GEN-LAST:event_aj_salActionPerformed

    private void aff_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aff_profActionPerformed
     
      if(evt.getSource()==aff_prof){
            aff_prof af_p=new aff_prof();
            desktopPane.add(af_p);
            af_p.setVisible(true);
         
        }
    }//GEN-LAST:event_aff_profActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Ecole_privé.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Ecole_privé.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Ecole_privé.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Ecole_privé.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion_Ecole_privé().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aff_c;
    private javax.swing.JButton aff_e;
    private javax.swing.JButton aff_prof;
    private javax.swing.JButton affiche_e_c;
    private javax.swing.JButton aj_classe;
    private javax.swing.JButton aj_pay;
    private javax.swing.JButton aj_prof;
    private javax.swing.JButton aj_sal;
    private javax.swing.JButton ajoute_e;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton ok_absence;
    private javax.swing.JButton ok_p;
    private javax.swing.JButton sup_e;
    private javax.swing.JButton sup_pr;
    // End of variables declaration//GEN-END:variables

}
